# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.0

jobs:
  site:
    docker:
      - image: circleci/php:7.2

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo 'hello'