# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.0

jobs:
  push_dev:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: git remote add acquia diffygithub@svn-6234.devcloud.hosting.acquia.com:diffygithub.git
      - run: git push acquia master
      - run: sleep 20
      - run: ssh diffygithub.dev@free-7955.devcloud.hosting.acquia.com 'cd /var/www/html/diffygithub.dev/docroot && drush cr'
  push_stage:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: git remote add acquia diffygithub@svn-6234.devcloud.hosting.acquia.com:diffygithub.git
      - run: git push acquia staging
      - run: sleep 20
      - run: ssh diffygithub.test@free-7955.devcloud.hosting.acquia.com 'cd /var/www/html/diffygithub.test/docroot && drush cr'
workflows:
  version: 2
  build-deploy:
    jobs:
      - push_dev:
          filters:
            branches:
              only: master
      - push_stage:
          filters:
            branches:
              only: staging